# Staging-specific values for your Node.js application.
# This file overrides values in the default values.yaml for the staging environment.

replicaCount: 2

image:
  tag: "staging"

nameOverride: "node-app-staging"
fullnameOverride: "node-app-staging"

service:
  type: NodePort

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: staging-node-app.example.com
      paths: ["/"]

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 150m
    memory: 200Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
  # targetMemoryUtilizationPercentage: 70

# Staging environment might have different node selectors or tolerations
nodeSelector: {}

tolerations: []

affinity: {}
