# You can encrypt the file with the plugin:
# 
# $ helm secrets enc secrets.yaml
# Encrypting secrets.yaml
# Encrypted secrets.yaml

apiVersion: 'kubernetes-client.io/v1'
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc }}
  POSTGRES_DB: {{ .Values.postgres.database | b64enc }}
