# You can encrypt the file with the plugin:
# 
# $ helm secrets enc secrets.yaml
# Encrypting secrets.yaml
# Encrypted secrets.yaml

apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ include "my-application.fullname" . }}
  labels:
    {{- include "my-application.labels" . | nindent 4 }}
spec:
  backendType: [backend_type] # e.g., 'secretsManager', 'systemManager', 'vault', etc.
  data:
    - key: [external_secret_key] # The key name in the external secret management system
      name: DB_PASSWORD # The key name in the Kubernetes Secret
      property: [property_name] # Optional: specific property in the external secret
      # Add other keys as needed
