apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "my-application.serviceAccountName" . }}
  labels:
    {{- include "my-application.labels" . | nindent 4 }}
{{- if .Values.serviceAccount.annotations }}
annotations:
  {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}
